### ISSUE TITLE
Pluralization issue with certain languages

### ISSUE THREAD

**Issue by dangerdogz** [solidusio-contrib/solidus_i18n#58]
Reference 

[I18n Issue](https://github.com/svenfuchs/i18n/issues/239)
[ActiveAdmin Issue](https://github.com/activeadmin/activeadmin/pull/2791)
[Spree Issue](https://github.com/spree/spree/issues/5842)
[Spree Issue](https://github.com/spree/spree/pull/6059)

**Summary**

Basically, english use this function to generate plural names
[Rails i18n link](https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/common_pluralizations/one_other.rb)
/one_other.rb
```ruby
module RailsI18n
  module Pluralization
    module OneOther
      def self.rule
        lambda { |n| n == 1 ? :one : :other }
      end

      def self.with_locale(locale)
        { locale => {
            :'i18n' => {
              :plural => {
                :keys => [:one, :other],
                :rule => rule }}}}
      end
    end
  end
end
```

And some other languages like french use this one
[Rails i18n link](https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/common_pluralizations/one_upto_two_other.rb)
```ruby
module RailsI18n
  module Pluralization
    module OneUptoTwoOther
      def self.rule
        lambda { |n| n && n >= 0 && n < 2 ? :one : :other }
      end

      def self.with_locale(locale)
        { locale => {
            :'i18n' => {
              :plural => {
                :keys => [:one, :other],
                :rule => rule }}}}
      end
    end
  end
```

**Issue**

Throughout Solidus, the pluralization is triggered with this format :  ```<%= Spree::PromotionCategory.model_name.human(count: :many) %>```

It works with the english OneOther even if n is a symbol (:many) because :symbol == 1 will just return false (so you get the :other), but it crashes when you try to use another pluralization method because it's trying to determine if n ( a symbol, :many) is less or greater than an integer, thus you get :   ``` (comparison of Symbol with 0 failed)``` because you can't use this operator with a symbol

**Comment by Murph33** [comment]
Sorry just a quick check, is it JUST the `(count: :many)` call that doesn't work, or are we having problems with all of the `(count: :other)` calls as well?  `(count: :many)` occurs only once in the code so that would be a quick fix.

**Comment by dangerdogz** [comment]
:other too, I just took this one as an example sorry. The issue is that it's a symbol so no difference between :other or :many

**Comment by tvdeyen** [comment]
The only way to fix this is to pass in an actual number, right? Good catch and great investigation @dangerdogz

This actually should be an issue on solidusio/solidus

**Comment by dangerdogz** [comment]
Continuing the discussion in the Solidus repo.
