### ISSUE TITLE
Make a new release to Rubygems

### ISSUE THREAD

**Issue by otlaitil** [solidusio-contrib/solidus_i18n#76]
Hello! Could you please push the new `1.1.0` release to rubygems? Seems that version 1.1.0 is not available there (https://rubygems.org/gems/solidus_i18n). 

Thanks!

**Comment by baron** [comment]
Would be nice to have.

**Comment by tvdeyen** [comment]
Here you go https://rubygems.org/gems/solidus_i18n/versions/1.1.0

Sorry for the delay 🐻

**Comment by baron** [comment]
thank you so much!
