### ISSUE TITLE
runtime dependency of rails-i18n set in gemspec prevents an update to solidus 2.0 (and rails 5)

### ISSUE THREAD

**Issue by bosskovic** [solidusio-contrib/solidus_i18n#85]
Hi, I'm trying to update our app to solidus 2.0 (and rails 5), but a dependency in the gemspec of solidus_i18n seems to be preventing that:

``` 
  s.add_runtime_dependency 'rails-i18n', '~> 4.0.1'
```

Should I make a PR that updates the version, if it's as simple as that?

**Comment by tvdeyen** [comment]
Yes, but make sure old versions are still supported. So, best bet is something like:

```ruby
s.add_runtime_dependency 'rails-i18n', ['>= 4.0.1', '< 6']
```
